version: "3.9"

networks:
  mvphrm_net:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    container_name: mvphrm_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    depends_on:
      - backend
    networks:
      - mvphrm_net

  backend:
    build: ./backend
    container_name: mvphrm_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_URL_SYNC: ${DATABASE_URL_SYNC}
      PORT: ${PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      FRONTEND_URL_PROD: ${FRONTEND_URL_PROD}
    depends_on:
      - db
    networks:
      - mvphrm_net

  db:
    build: ./db
    container_name: mvphrm_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mvphrm_net

volumes:
  db_data:
